spring:
  application:
    name: paymentadapter

resilience4j:
  circuitbreaker:
    instances:
      paymentGateway:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        ignoreExceptions:
          - com.cordilleracoffee.paymentadapter.application.exception.InvalidPaymentException
        ignore-exception-predicate:
          - com.cordilleracoffee.paymentadapter.config.IgnoreExceptionPredicate

api:
  client:
    payment-gateway-url: ${PAYMENT_GATEWAY_API}